declare const styles: {
    storyBrowser: string;
    welcome: string;
    welcomeImage: string;
    filters: string;
    links: string;
    filtersContainer: string;
    filtersSearch: string;
    partnerSearch: string;
    filterSearch: string;
    activate: string;
    filtersDropdown: string;
    filtersOptions: string;
    FirstRow: string;
    show: string;
    fadeIn: string;
    uncheck: string;
    filterOptions: string;
    featuredItems: string;
    sortResults: string;
    sortBtn: string;
    items: string;
    viewBtn: string;
    item: string;
    viewStory: string;
    itemTitle: string;
    itemSolution: string;
    itemPartner: string;
    itemIndustry: string;
    itemType: string;
    itemDate: string;
    image: string;
    itemList: string;
    filterContainer: string;
};
export default styles;
//# sourceMappingURL=StoryBrowser.module.scss.d.ts.map